<?php

namespace AppBundle\Repository;

/**
 * CardCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CardCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
