<?php

namespace AppBundle\Repository;

/**
 * CardToCategoryRepositories
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CardToCategoryRepositories extends \Doctrine\ORM\EntityRepository
{
}
