app:
    resource: '@AppBundle/Controller/'
    type: annotation

# Sonata Admin Route
admin_area:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

